name: Update GitHub Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Every midnight
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README with latest stats
        run: echo "Stats auto-updated on $(date)" >> README.md
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "♻️ Auto update stats" || exit 0
          git push